### ISSUE TITLE
Output of external commands gets printed to stdout

### ISSUE THREAD

**Issue by SitiSchu** [amodm/webbrowser-rs#20]
In my case on Linux the call to `xdg-open` causes `Opening in existing browser session` to be printed to the console. Would it make sense to silence all output of the external tools by default unless there's an error?

**Comment by amodm** [comment]
Makes sense. Probably better with a flag (defaulted to false) that can be enabled to switch on the output.

**Comment by zwhitchcox** [comment]
Workaround:

Add to your Cargo.toml

```
[dependencies]
webbrowser = { git = "https://github.com/codota/webbrowser-rs", branch = "feature/add-suppress-output-flag-with-docs" }
```

In your code:

```rs
use webbrowser::{self, BrowserOptions};

    if webbrowser::open_browser_with_options(
      BrowserOptions {
        url: String::from(token_url),
        suppress_output: Some(true),
        browser: Some(webbrowser::Browser::Default),
      }).is_ok() {}
```

**Comment by zwhitchcox** [comment]
Ultimately should merge #22 though

**Comment by SDAChess** [comment]
Hello! I am having the same issue here, bump to merge ? :)

**Comment by amodm** [comment]
Fixed in https://github.com/amodm/webbrowser-rs/commit/ecfbf66daa0cc139bd557bd7899a183bd6575990. By default, we now suppress output for all GUI browsers. This behaviour can be overridden. See [Consistent Behaviour](https://github.com/amodm/webbrowser-rs#consistent-behaviour) section for details.
