### ISSUE TITLE
Not working for some browsers

### ISSUE THREAD

**Issue by Eoin-McMahon** [amodm/webbrowser-rs#24]
So I have tested this with Firefox, Chrome and notably Min browser (which is the one i personally use). I changed my default browser each time when running my rust code and firefox and chrome work fine, however min browser displays "An error  occurred (-102)" but if i refresh the page it loads properly. 

I'm not sure if this a fault with webbrowser-rs or min but i thought i would put this issue up anyway just in-case.

**Comment by amodm** [comment]
Can you share which platform, and code to reproduce?

**Comment by Eoin-McMahon** [comment]
![image](https://user-images.githubusercontent.com/35693672/85150219-c7a02100-b241-11ea-9546-2bdd6ffaff55.png)
Here is the code, CLIENT_ID and CLIENT_SECRET are set environment variables.

As i said, this is taken straight out of the example for github. Also to note, I am running arch linux. The localhost server is also set up through github apps

**Comment by amodm** [comment]
Tried this on Mint Linux just now (with Min browser as preferred), and it works fine. I suspect this is a Min issue, or an environment issue.

I'll leave this issue open for a week in case you're able to figure out a better step to reproduce, or if you're able to identify this as some environmental interference that `webbrowser` needs to guard against. Will close post that.

**Comment by amodm** [comment]
@Eoin-McMahon were you able to investigate this more? If not, I'll be looking to close this.
