### ISSUE TITLE
add support for wasm

### ISSUE THREAD

**Issue by hosseind2** [amodm/webbrowser-rs#25]
<img width="925" alt="Screen Shot 2020-06-25 at 6 21 17 PM" src="https://user-images.githubusercontent.com/57390535/85732488-aa22f980-b710-11ea-9165-755317d21d8b.png">
I have a project that I want to make a web application with rust and wasm
and I want to install rspotify package, it installs correctly but after run webpack
I face with this issue that I guess this package has no support for wasm

can you please add support for wasm?

**Comment by YerinAlexey** [comment]
@hosseind2 WASM is already supported but it was not released so you need to build library from master.

**Comment by hosseind2** [comment]
> @hosseind2, WASM is already supported but was not released so you need to build library from master. `rspotify` don't use git version of `webbrowser` and needs to be patched for that

yeah my pull is merged, there is something about CI, I will wait for it
thanks

**Comment by amodm** [comment]
@YerinAlexey this is out as [0.5.5](https://crates.io/crates/webbrowser/0.5.5)
