### ISSUE TITLE
Run silently

### ISSUE THREAD

**Issue by zwhitchcox** [amodm/webbrowser-rs#32]
Is there anyway to run this command silently? I'm writing a terminal program, and whenever it opens the browser, it outputs a bunch of stuff to the console:

```
(chrome:393290): Gtk-WARNING **: 14:08:45.919: Theme parsing error: gtk.css:1566:23: 'font-feature-settings' is not a valid property name

(chrome:393290): Gtk-WARNING **: 14:08:45.922: Theme parsing error: gtk.css:3616:25: 'font-feature-settings' is not a valid property name

(chrome:393290): Gtk-WARNING **: 14:08:45.922: Theme parsing error: gtk.css:4078:23: 'font-feature-settings' is not a valid property name
Opening in existing browser session.
```

Is there any way to get rid of that? I don't care if it fails, because I'm going to be pasting the URL to the console anyway as a backup.

**Comment by zwhitchcox** [comment]
Nevermind, I see this is a duplicate of #20

**Comment by amodm** [comment]
This is now addressed. See relevant comment here: https://github.com/amodm/webbrowser-rs/issues/20#issuecomment-1045970562
