### ISSUE TITLE
all `open_browser()` calls should block

### ISSUE THREAD

**Issue by getreu** [amodm/webbrowser-rs#33]
Similar to issue #13, I observed, that under Windows `open_browser()`-calls return immediately, while the same call under Linux blocks.

In my opinion they **all should block**. This way the caller gets to know when the browser is closed by the user. This way also use cases where blocking is not wanted, are covered easily: just launch a thread and call `open_browser()`.

**Comment by amodm** [comment]
Given that there's no guaranteed IPC mechanism available to know when the browser gets closed, I'm currently of the opinion to standardise on returning immediately as a behaviour, instead of the alternate. The only exception would be a pure console env, where  by nature of the environment, it's expected to be blocking.

If you feel otherwise, please share a proposal on why, and a mechanism of how. If not, will be closing this out.

**Comment by getreu** [comment]
My use case: [Tp-Note](https://blog.getreu.net/projects/tp-note/) first starts a web server and then binds a web browser to that port. When the user closes the browser the server shuts down.
Usually `child.wait()` blocks until the process finished. Some applications fork when they start, e.g. `vim` but they often provide an option not to do so (`--no-fork`).

**Comment by getreu** [comment]
Ok, it seems, that Firefox under Windows forks. I vaguely remember, there was a command line option `/W` for wait, but I had no time to test it.

**Comment by getreu** [comment]
Under Windows, it seems, that  [child.wait()](https://doc.rust-lang.org/std/process/struct.Child.html#method.wait) does not work with browsers, as it returns immediately. This means Windows should be treated separately with the Windows API. 

I see two possibilities (see also [code examples](https://github.com/DoumanAsh/windows-win-rs/blob/master/tests/windows.rs)):

1. Poll in a loop the process ID: [windows_win::Process - open()](https://docs.rs/windows-win/2.4.0/windows_win/struct.Process.html#method.open)
2. Poll in a loop the process's window: [windows_win::Process - window()](https://docs.rs/windows-win/2.4.0/windows_win/struct.Process.html#method.window) gives an `Option` with the Window associated to that process.

**Comment by getreu** [comment]
Someone knowing the Windows API better could help here. Any ideas?

**Comment by getreu** [comment]
I found the solution: we need a `Job` object and assign the handle of our `Child` to it.
Then `job.query_process_id_list()?.len() > 0` means, that there are still open browser windows.

See details here:
[tp-note/process_ext.rs at master · getreu/tp-note](https://github.com/getreu/tp-note/blob/master/src/process_ext.rs)

**Comment by getreu** [comment]
With Firefox under Linux I observed the following:
when you open a second  Firefox, the process sends an IPC message to the first and then terminates immediately.

**Comment by amodm** [comment]
Closing this out as implementation of this in a predictable way is very tricky.
