### ISSUE TITLE
url parameter is treated as file link if the last character is a space

### ISSUE THREAD

**Issue by deg0nz** [amodm/webbrowser-rs#34]
I had the issue, that the URL was treated as a file link, if it contains a space at the end.

For example:

My URL is `let url = "http://example.com/foo "`.
When I call `webbrowser::open(url)`, I get the error `The file /path/to/current/directory/http:/example.com/foo   does not exist.`.

Maybe there should be some kind if URL validation to determine, if the given String is actually a valid URL?
Or maybe some logic that determines, if the given `str` is a file path and then converts it to an actual `file://` path?

**Comment by amodm** [comment]
Handling URL encoding/validation should be a user input stage check, than a library level check. As an example, if you were to look at [python's webbrowser library](https://github.com/python/cpython/blob/3.9/Lib/webbrowser.py), you'd find no URL encoding done either.

**Comment by amodm** [comment]
@deg0nz commit https://github.com/amodm/webbrowser-rs/commit/11789ddfe36264bbbe7d596ab61e3fff855c3adb should fix this. I'd made that commit for handling unicode chars, but should help here too.
