### ISSUE TITLE
Feature Request: window size and position

### ISSUE THREAD

**Issue by nyvs** [amodm/webbrowser-rs#36]
I think it would be cool to have the possibility to open the webbrowser in a small window,
and for ex. in the middle of the screen.

Would be useful for oauth and oidc auth flows.

Would a pr be welcome?

**Comment by amodm** [comment]
If it's possible, yes, a PR would be welcome. But I'm not sure if it is.

**Comment by amodm** [comment]
You can open a PR separately if you're able to figure out a mechanism for it. Closing this one.
