### ISSUE TITLE
Problem with Powershell on Windows 10

### ISSUE THREAD

**Issue by Shadlock0133** [amodm/webbrowser-rs#4]
Webbrower on Windows uses "start link URL" which in Powershell on Windows 10 returns error "The system cannot find the file specified". After testing it seems the problem might be with link part.

[This](https://social.technet.microsoft.com/Forums/windowsserver/en-US/e54555bd-00bb-4ef9-9cb0-177644ba19e2/how-to-open-url-through-powershell?forum=winserverpowershell) proposes many different answers, some (e.g. "Start-Process -Path URL") don't work any more or default to Internet Explorer.

**Comment by amodm** [comment]
[This article](https://www.dwheeler.com/essays/open-files-urls.html) seems to indicate that the right way to open URLs on Windows is `start https://google.com`.

I just checked on Windows 10, and `start https://google.com` seems to work on both Command Prompt as well as PowerShell.

I don't know enough about Windows to know how far back this would go, but am inclined to go ahead with this change. Please suggest if you have better ideas.

**Comment by amodm** [comment]
Thanks to @wariuni who had this fixed already.
