### ISSUE TITLE
detect if browser is available without opening a url

### ISSUE THREAD

**Issue by coloradocolby** [amodm/webbrowser-rs#46]
Just as the title says, I would love it if there was a way to detect if a browser is available without having to open a url. 

I have an app that can be run in docker, where a browser is not available. If possible I'd like t remove the web feature from my app, but I can't easily detect if a browser is available without attempting to open a url.

**Comment by amodm** [comment]
I'm guessing something like `Browser::is_available()` should work.

**Comment by coloradocolby** [comment]
@amodm you're awesome! I'm using this in the current release of [thokr](https://github.com/coloradocolby/thokr) 🚀 

Thanks for such a speedy turnaround!

**Comment by amodm** [comment]
That's kind of you @coloradocolby. Glad that this is being used in thokr, the UI looks so cool 👍🏼
