### ISSUE TITLE
Promote to v1.0.0 if no API changes by Mar 1st, 2024

### ISSUE THREAD

**Issue by amodm** [amodm/webbrowser-rs#50]
Reasons to do so:
1. Current API has been stable for a while
2. Consistent behaviour is [defined reasonably strictly](https://tv.apple.com/in/show/the-ipcress-file/umc.cmc.274qjpty163a1xjwab1ft7kbl), and seems unlikely to change for a while
3. As per [pre-release guidelines](https://doc.rust-lang.org/cargo/reference/resolver.html#pre-releases) of Cargo, `It is recommended to not use pre-release dependencies in a library if your library is not also a pre-release`, so this should make for easier decision to include in your manifest.

**Comment by amodm** [comment]
Specific changes when releasing v1.0.0:
* Specify `rust-version` in `Cargo.toml` as a best practice.
* Remove [clippy.toml](https://github.com/amodm/webbrowser-rs/commit/48c577c8bac5510019fe8fd469ceeeae8aa3f41a) as `rust-version` will do the same job

**Comment by amodm** [comment]
Move this out to Mar 1st, given the recent changes.

**Comment by torokati44** [comment]
Ping! :) It's now the middle of April!

**Comment by amodm** [comment]
Yeah, I've been sitting on it for too long. Will do it this weekend.

**Comment by amodm** [comment]
[v1.0.0](https://github.com/amodm/webbrowser-rs/releases/tag/v1.0.0) is now out.

**Comment by torokati44** [comment]
Awesome, thank you! c:
