### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by benharvie** [amodm/webbrowser-rs#59]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@offalltn) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by amodm** [comment]
This is added. You may report the issue as per the details in [SECURITY.md](https://github.com/amodm/webbrowser-rs/blob/main/SECURITY.md) I'm assuming this is different than the issue reported by @offalltn already, which was fixed & acknowledged in [v0.8.3](https://github.com/amodm/webbrowser-rs/releases/tag/v0.8.3)
