### ISSUE TITLE
Add other applications for Quest

### ISSUE THREAD

**Issue by mvvvv** [amodm/webbrowser-rs#81]
Hello, your crate works well on the Meta Quest VR Headset. As you can see here : https://youtu.be/28H67HftB_E 

On the Quest devices this could allow to open a dozen 2D applications such as the Browser, YouTube 2D, the parameters etc ...  over a VR application in progress, 

Would it be possible to extend your code to other configurable applications? If not, do  you allow me to take up your code to adapt it to my project under MIT license.

I believe this code should be sufficient : https://github.com/amodm/webbrowser-rs/blob/main/src/android.rs

Thanks.

**Comment by amodm** [comment]
Under MIT license, you're always free to copy any part of the code and modify it as you please. Credit would be appreciated, but not strictly necessary.

Given the above liberty, I appreciate you checking in. I'll be able to comment better on acceptability of a PR for this, if you can share what such an API should look like.

**Comment by mvvvv** [comment]
It is definitely better than the code remains in your crate. I will try to find the best solution in a fork.

**Comment by amodm** [comment]
Please reopen if/when you feel you have an answer.
